// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB980HaI2P4YJKj9oGdtyA7pM-VHZTOIGo',
    appId: '1:726059957937:web:55931b1f12c3b87de1ec90',
    messagingSenderId: '726059957937',
    projectId: 'teddy-fx712',
    authDomain: 'teddy-fx712.firebaseapp.com',
    storageBucket: 'teddy-fx712.firebasestorage.app',
    measurementId: 'G-WVZXJFWRHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-R_g6zsEnNIAped_wM3emUD_mduNpH8c',
    appId: '1:726059957937:android:3e848b0b72100119e1ec90',
    messagingSenderId: '726059957937',
    projectId: 'teddy-fx712',
    storageBucket: 'teddy-fx712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcs_E_OnoFwK2P6MNhBaSoT3nvSYlokCk',
    appId: '1:726059957937:ios:d0e9b669d607be99e1ec90',
    messagingSenderId: '726059957937',
    projectId: 'teddy-fx712',
    storageBucket: 'teddy-fx712.firebasestorage.app',
    iosClientId: '726059957937-0s3iiiisucv0b08ven01c7htrhhk4kv6.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.teddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcs_E_OnoFwK2P6MNhBaSoT3nvSYlokCk',
    appId: '1:726059957937:ios:d0e9b669d607be99e1ec90',
    messagingSenderId: '726059957937',
    projectId: 'teddy-fx712',
    storageBucket: 'teddy-fx712.firebasestorage.app',
    iosClientId: '726059957937-0s3iiiisucv0b08ven01c7htrhhk4kv6.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.teddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB980HaI2P4YJKj9oGdtyA7pM-VHZTOIGo',
    appId: '1:726059957937:web:c2c1fc71235e0bd9e1ec90',
    messagingSenderId: '726059957937',
    projectId: 'teddy-fx712',
    authDomain: 'teddy-fx712.firebaseapp.com',
    storageBucket: 'teddy-fx712.firebasestorage.app',
    measurementId: 'G-LMLPP9NR9Y',
  );
}
